[book]
authors = ["Francisco Perez-Sorrosal & Martin Lange"]
language = "en"
src = "src"
title = "mdbook-bib Manual"

[build]
build-dir = "public"

[output.html]
default-theme = "theme"
git-repository-url = "https://github.com/francisco-perez-sorrosal/mdbook-bib"

[preprocessor.bib]
bibliography = "bibliography.bib"
title="References" # Custom title
hb-tpl = "render/my_references.hbs"
cite-hb-tpl = "render/my_cite.hbs"
css = "render/my_style.css"
add-bib-in-chapters = true
